db:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    db: lemoncash?useSSL=false&useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: sa
    password: password
    maxLifetime: 420000
    idleTimeout: 60000
    maximumPoolSize: 200
    leakDetectionThreshold: 0
    prepStmtCacheSize: 250
    cachePrepStmts: true
    cacheServerConfiguration: true
    connectionTimeout: 30000
    minimumIdle: 25
    initialization-mode: embedded