db:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-test:3306/test-lemoncash?useSSL=false&allowPublicKeyRetrieval=true
    username: sa
    password: password
    maxLifetime: 420000
    idleTimeout: 60000
    maximumPoolSize: 200
    leakDetectionThreshold: 0
    prepStmtCacheSize: 250
    cachePrepStmts: true
    cacheServerConfiguration: true
    connectionTimeout: 30000
    minimumIdle: 25

spring:
  datasource:
    initializationMode: never