INSERT INTO COIN_TYPE
(`NAME_ABBR`,`NAME`,`FORMAT`)
SELECT
'ARS', 'Peso Argentino', '0.00';

INSERT INTO COIN_TYPE
(`NAME_ABBR`,`NAME`,`FORMAT`)
SELECT
'USDT', 'Tether', '0.00';

INSERT INTO COIN_TYPE
(`NAME_ABBR`,`NAME`,`FORMAT`)
SELECT
'BTC', 'Bitcoin', '0.00000000';
