CREATE TABLE IF NOT EXISTS `USER`
(
  `USER_ID`      bigint(20)   NOT NULL AUTO_INCREMENT,
  `NAME`         varchar(50)  NOT NULL,
  `SURNAME`      varchar(50)  NOT NULL,
  `ALIAS`        varchar(100) NOT NULL,
  `EMAIL`        varchar(100) NOT NULL,
  `STATUS`       int(2)       NOT NULL DEFAULT '1',
  `LAST_UPDATED` datetime              DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `ALIAS_UN` (`ALIAS`),
  UNIQUE KEY `EMAIL_UN` (`EMAIL`)

);

CREATE TABLE IF NOT EXISTS `COIN_TYPE`
(
  `COIN_TYPE_ID` int(3)      NOT NULL AUTO_INCREMENT,
  `NAME_ABBR`    varchar(5)  NOT NULL,
  `NAME`         varchar(50) NOT NULL,
  `FORMAT`       varchar(25) DEFAULT NULL,
  `LAST_UPDATED` datetime    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`COIN_TYPE_ID`),
  UNIQUE KEY `NAME_ABBR` (`NAME_ABBR`)

);

CREATE TABLE IF NOT EXISTS `WALLET`
(
  `WALLET_ID`    bigint(20)     NOT NULL AUTO_INCREMENT,
  `BALANCE`      decimal(24, 8) NOT NULL DEFAULT 0.0,
  `COIN_TYPE_ID` int(5)         NOT NULL,
  `LAST_UPDATED` datetime                DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`WALLET_ID`),
  FOREIGN KEY (`COIN_TYPE_ID`) REFERENCES `COIN_TYPE` (`COIN_TYPE_ID`)
);

CREATE TABLE IF NOT EXISTS `USER_WALLET`
(
  `USER_WALLET_ID` bigint(30) NOT NULL AUTO_INCREMENT,
  `USER_ID`        bigint(20) NOT NULL,
  `WALLET_ID`      bigint(20) NOT NULL,
  `LAST_UPDATED`   datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_WALLET_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`),
  FOREIGN KEY (`WALLET_ID`) REFERENCES `WALLET` (`WALLET_ID`)
);

CREATE TABLE IF NOT EXISTS `MOVEMENT`
(
  `MOVEMENT_ID`           bigint(30)     NOT NULL AUTO_INCREMENT,
  `MOVEMENT_TYPE`         varchar(10)    NOT NULL,
  `ORIGIN_WALLET_ID`      bigint(20)              DEFAULT NULL,
  `DESTINATION_WALLET_ID` bigint(20)              DEFAULT NULL,
  `COIN_TYPE_ID`          int(3)                  DEFAULT NULL,
  `AMOUNT`                decimal(24, 8) NOT NULL DEFAULT 0.0,
  `LAST_UPDATED`          datetime                DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`MOVEMENT_ID`),
  FOREIGN KEY (`ORIGIN_WALLET_ID`) REFERENCES `WALLET` (`WALLET_ID`),
  FOREIGN KEY (`DESTINATION_WALLET_ID`) REFERENCES `WALLET` (`WALLET_ID`),
  FOREIGN KEY (`COIN_TYPE_ID`) REFERENCES `COIN_TYPE` (`COIN_TYPE_ID`)
);

